### ISSUE TITLE
Use in Production?

### ISSUE THREAD

**Issue by lacymorrow** [sindresorhus/electron-util#14]
You make fantastic libraries. Would you recommend this one for use in a production node app, or would you use this only for development?

I only ask because of the line in your readme:

> Useful utilities for developing Electron apps...

Cheers!

**Comment by sindresorhus** [comment]
Yes, it's for production use.

It's used in multiple production apps:

- [Caprine](https://github.com/sindresorhus/caprine)
- [Kap](https://github.com/wulkano/kap)
- [HyperDex](https://github.com/atomiclabs/hyperdex)

I've improved the tagline now.

**Comment by lacymorrow** [comment]
You the man! Thanks for the response and all of your FANTASTIC modules. You're one of 5 devs I can count on for clean code (the other's being Abramov, Irish, Coyier, Verou, and Torvalds 🗡)
