### ISSUE TITLE
Publish `enforceMacOSAppLocation` as a standalone module

### ISSUE THREAD

**Issue by fabiospampinato** [sindresorhus/electron-util#17]
Can the `enforceMacOSAppLocation` function be published as a standalone module?

That's the only thing provided by this library that I'm using and I'd like to minimize the amount of extra code that is bundled along with my app.

**Comment by sindresorhus** [comment]
I don't think it's worth the overhead of a separate package, but I have been meaning to move features into separate files. Then you could just do `const x = require('electron-util/enforce-macos-app-location');`. Would that solve your problem?

**Comment by fabiospampinato** [comment]
Yes it should 👍

**Comment by sindresorhus** [comment]
It ended up being `const x = require('electron-util/source/enforce-macos-app-location');` When Electron supports ESM and we move to ESM here, tree-shaking should be possible with just `import {enforceMacosAppLocation} from 'electron-util');`, I think.
