### ISSUE TITLE
Dark Mode on Windows

### ISSUE THREAD

**Issue by ImedAdel** [sindresorhus/electron-util#18]
Windows currently supports Dark Mode. Although it is not supported by Electron yet, it seems possible (according to https://stackoverflow.com/a/51336913/3737308) to detect it.

Can it be added to `electron-util`? 😅

**Comment by sindresorhus** [comment]
For context: https://github.com/electron/electron/issues/15316

I don't really want to do this. Checking dark mode is not useful without the ability to be notified about changes, and there doesn't seem to be an easy way to achieve that. I'd rather just wait on Electron to figure it out.
