### ISSUE TITLE
Can't use with Next.js

### ISSUE THREAD

**Issue by slorenzo** [sindresorhus/electron-util#30]
Hi.

I can't use this library with Next.js. I see this error:
>Module not found: Can't resolve 'fs' in '/Users/slorenzo/Desktop/Development/noiser-desktop/node_modules/electron'

Is there any workaround?
Thanks!

**Comment by sindresorhus** [comment]
That is a problem with Next.js. You should open an issue there instead.

**Comment by lacymorrow** [comment]
@slorenzo that's usually an issue with trying to server-side render native modules. Make sure your code is being run only in the "Main" process.

**Comment by slorenzo** [comment]
Thanks @lacymorrow. I found out a workaround [here](https://github.com/zeit/next.js/issues/7755#issuecomment-508633125).But another error appears, so I decided not to use this package in the renderer process.

**Comment by lacymorrow** [comment]
No problem @slorenzo. If you're looking for a solution to build Electron with a statically-rendered React + Next.js app I can suggest [Nextron](https://github.com/saltyshiomix/nextron/).
