### ISSUE TITLE
Build error with Electron 10.1.2 and Angular 8.3.20

### ISSUE THREAD

**Issue by evansben87** [sindresorhus/electron-util#33]
Implement Electron app with Angular, Typescript, built project and got error import "AllElectron"
ERROR in node_modules/electron-util/index.d.ts:4:9 - error TS2305: Module '"electron"' has no exported member 'AllElectron'.

4 import {AllElectron, Remote, BrowserWindow, Size, Rectangle, Session, MenuItemConstructorOptions, MenuItem} from 'electron';

Please help me to fix this issue. Thanks.

**Comment by evereq** [comment]
@evansben87 please see our PR here: https://github.com/sindresorhus/electron-util/pull/34, it helps us to make this package to work with Electron 10
