### ISSUE TITLE
Option to ignore MacOS dock and Windows taskbar height when using `centerWindow()`

### ISSUE THREAD

**Issue by lacymorrow** [sindresorhus/electron-util#41]
Currently if the dock is present the application is centered relative to the available space minus the dock height. 

I would like to center my window relative to the total screen space. If I hide the dock or put it on another display the function works as expected.

**Comment by sindresorhus** [comment]
Sure. PR welcome. I think it's just about using `.bounds` instead of `.workArea` here: https://github.com/sindresorhus/electron-util/blob/805537252dd19aea28403a4f0841555b402ad7c8/index.js#L56 

https://www.electronjs.org/docs/api/structures/display
