### ISSUE TITLE
Will be compatible with electron@12.x ?

### ISSUE THREAD

**Issue by jackple** [sindresorhus/electron-util#45]
There is something changed at 12.x.  For example, the `remote` module.
Is there a plan for it?

https://github.com/electron/electron/pull/25293

**Comment by sindresorhus** [comment]
It's being worked on in https://github.com/sindresorhus/electron-util/pull/37.

**Comment by sindresorhus** [comment]
#37 went stale. So this is "pull request welcome" again.
