### ISSUE TITLE
Error with TypeScript (Module '"electron"' has no exported member 'AllElectron')

### ISSUE THREAD

**Issue by blaumeise20** [sindresorhus/electron-util#49]
I tried to use `mac-screen-capture-permissions` for my Electron app, and that package internally uses `electron-util`. When I compile it with TypeScript I get that error:

```
node_modules/electron-util/index.d.ts:4:9 - error TS2305: Module '"electron"' has no exported member 'AllElectron'.

4 import {AllElectron, Remote, BrowserWindow, Size, Rectangle, Session, MenuItemConstructorOptions, MenuItem} from 'electron';
          ~~~~~~~~~~~
```
I added `node_modules` to my exclude in tsconfig, but the error is still here. It seems like in new versions of Electron `AllElectron` does no longer exist.

**Comment by ysfscream** [comment]
+1 same issue!

**Comment by quuu** [comment]
same here!
