### ISSUE TITLE
Rename node.js to compile on Windows

### ISSUE THREAD

**Issue by mquevill** [sindresorhus/electron-util#51]
It seems that Windows does not like a file being named "node.js". I get the below error when trying to run `npm start` for the example app on Windows. Simply renaming this file to "nodenew.js" in my testing allowed the example app to be built.

The error from "Windows Script Host":
```
Script: .\electron-util\node.js
Line:   9
Char:   38
Error:  Syntax error
Code:   800A03EA
Source: Microsoft JScript compilation error
```

The line in question is a valid line, but the error is thrown at the `=>` operator:
```javascript
exports.fixPathForAsarUnpack = path => exports.isUsingAsar ? path.replace('app.asar', 'app.asar.unpacked') : path;
```

**Comment by sindresorhus** [comment]
I don't have any interest in working around weird Windows problems.
