### ISSUE TITLE
Error reported in renderer process

### ISSUE THREAD

**Issue by sage-z** [sindresorhus/electron-util#52]
The 'is.development' variable uses the 'electron-is-dev' package, but this package 'must be used from the Electron main process'.

As a result, I won't be able to use 'electron-util' in my renderer process.

**Comment by sindresorhus** [comment]
> The 'is.development' variable uses the 'electron-is-dev' package, but this package 'must be used from the Electron main process'.


`electron-util` uses an older version of that package which can be used in either process. I think you're problem is rather that you're using the latest Electron, which doesn't enable the `remote` module by default.

https://github.com/sindresorhus/electron-util/pull/37

**Comment by sage-z** [comment]
> > The 'is.development' variable uses the 'electron-is-dev' package, but this package 'must be used from the Electron main process'.
> 
> `electron-util` uses an older version of that package which can be used in either process. I think you're problem is rather that you're using the latest Electron, which doesn't enable the `remote` module by default.
> 
> #37

Yes, not only that, statements like "process.platform === 'Darwin'" are not valid in the Renderer process, because there are no process objects in the Renderer process.

It may also have something to do with my use of Webpack and TypeScript builds...

**Comment by vraravam** [comment]
I have the same problem - unable to upgrade to `electron` v14 since it fails with the same issue here. Can we have a version of `electron-util` that uses v2.0.0 of `electron-is-dev`?

**Comment by vraravam** [comment]
any updates on this please? This is harming us from upgrading to electron v14.
