### ISSUE TITLE
Please, make "showAboutWindow" more useful

### ISSUE THREAD

**Issue by Andrew-web-coder** [sindresorhus/electron-util#59]
Hi, I am using you utils (on Windows) and here are my comments:

1) Icon is poor quality (I even tried very large PNG file);
2) Text is not centered, in fact, it does look very different compared to the screenshot on the page of this project;
3) I am puzzled about how to change title - it seems to use "name" from "package.json", but that is lower cased with the dashes, e.g., it shows "my-app", but, obviously, I want to have "My App".
4) Why there is limitation about "website"? To me, it seems obvious, that everyone would want to display link to project homepage.

Thanks!

**Comment by Andrew-web-coder** [comment]
One more thing- the window should me modal, I can open it multiple times.

**Comment by sindresorhus** [comment]
These things are problems with Electron, not this package. This package simply wraps its API: https://github.com/sindresorhus/electron-util/blob/f5440bbe2527eaaa338e0df3e2038c60221929ea/index.js#L197-L229

You will need to open an isuse on Electron.
